# Generated by Django 5.1.2 on 2024-11-01 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_item_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='category',
            new_name='category_id',
        ),
    ]
