# Generated by Django 5.1.2 on 2024-11-01 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_category_item_category_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='category_id',
            new_name='category',
        ),
    ]
