# Generated by Django 5.1.2 on 2024-11-05 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_item_createdby'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='units',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
