# Generated by Django 5.1.2 on 2024-11-08 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_item_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-name']},
        ),
    ]
